name: CI

on:
  push:
    branches:
      - dev
      - stage
      - prod

jobs:
   deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
      - name: Npm install & npm build
        run:  |
            npm install
            npm run lint
            npm run prettier
            Cl=true npm run test

      - name: Build for dev
        if: github.ref == 'refs/heads/dev'
        run: npm run build:dev

      - name: Build for stage
        if: github.ref == 'refs/heads/stage'
        run: npm run build:stage

      - name: Build for prod
        if: github.ref == 'refs/heads/prod'
        run: npm run build:prod
      
      - name: S3 Sync
        uses: jakejarvis/s3-sync-action@v0.5.1 
     
        env:
           AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_REGION: 'ap-south-1'
           SOURCE_DIR: 'dist/ng-fundamentals'
